language: python
cache: pip
sudo: false
python:
- '3.6'
- '3.5'
- '2.7'
- pypy
env:
  # Lowest supported version
  - MARSHMALLOW_VERSION="==2.7.0"
  # Latest release
  - MARSHMALLOW_VERSION=""
install:
- travis_retry pip install -r dev-requirements.txt
- travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then invoke test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 3.6* ]]; then invoke test --no-lint; fi
jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: '3.6'
    env: []
    before_install: true
    install: true
    script: echo "Releasing to PyPI..."
    after_success: true
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: ptcK+xOvW1G+hJnK/7mG99iDQeSfYn/bmDXJ6ay0rRa8fBHAxdiBrrUM3m4UVhJmvCvEX4R8MqLEotj88QWJa3fykAssD8Zh9VXSj0HyzswzMZMGDM2/3SWIFLGhpCn6bkPMGGUU7USDtwZg6HPHrgtNCxdjvERXbB3Nfram03hJB317jzk3XlhXRiekh9S1KvlpkMSveziSRjJQP51TmBYybewkmfqTsUDtgmaUtCWuIDhCJmHAZ3C2FYQ/QVv2vV2iffBpywG3bZ9BonabaPMp3oK8wG+aZPSaTb0KvW7UUvEqwN2FFEngJy6aQSak+O/b2XtV20NlPT0jz/8SC4DY+wYpDbRYoMq8XVEkKRtyGvKdH9tqVhgnfBi8vbjMzmwVGYjfkkOprZh+Hb83viwt093z2wPOkvkXL/fpVRMKCF22TjW2yVIP73yv+JCPCFC6+RHNBkUY+LxbbWPQ9SjndyylrnoAehXhZPQzZ+du/K8J9evyfVheqfFsu5Cci28QCG+YUevBqA62HvC3cwmoHvSnTtC5tlZhlQPrUmqt9k1ZkSv7hSqHcw3wI5H81MHCkfJPNlls4q5hqCL3VyValOYG5sCYgWv6E7j7GclXoQmwQ/A46rgaf5FsXXh8TylZtAK5oSQA2EJxbdk5Dcze4l5EpcFSaH5w5DbQu5o=
